USE PROJETO_SAD

--1.	Qual o montante recebido por cada funcionário por mês?
	SELECT SUM(P.VALOR) AS VALOR, F.NOME, T.NOMEMES FROM DW.FATO_PAGAMENTO P
	INNER JOIN DW.DIM_TEMPO T ON (P.ID_DATA_PAGAMENTO = T.ID_TEMPO)
	INNER JOIN DW.DIM_FUNCIONARIO F ON (F.ID_FUNCIONARIO = P.ID_FUNCIONARIO)
	GROUP BY F.NOME, T.NOMEMES

--2.	Qual o montante vendido por cada funcionário por semana? 
	SELECT SUM(D.VALOR) AS VALOR, T.ID_TEMPO FROM DW.FATO_DIVIDA D 
	INNER JOIN DW.DIM_TEMPO T ON (T.ID_TEMPO = D.ID_DATA_DIVIDA)
	GROUP BY ID_TEMPO

--3.	Qual o montante vendido por cada funcionário por mês?
	SELECT SUM(D.VALOR) AS VALOR, F.NOME, T.NOMEMES FROM DW.FATO_DIVIDA D 
	INNER JOIN DW.DIM_FUNCIONARIO F ON (D.ID_FUNCIONARIO = F.ID_FUNCIONARIO) 
	INNER JOIN DW.DIM_TEMPO T ON (D.ID_DATA_DIVIDA = T.ID_TEMPO) 
	GROUP BY T.NOMEMES, F.NOME

--4.	Qual o montante recebido pelo estabelecimento por mês? 
	SELECT SUM(D.VALOR), T.NOMEMES FROM DW.FATO_PAGAMENTO D 
	INNER JOIN DW.DIM_TEMPO T ON (D.ID_DATA_PAGAMENTO = T.ID_TEMPO) 
	GROUP BY T.NOMEMES
--5.	Qual o montante recebido pelo estabelecimento por ano?
	SELECT SUM(P.VALOR) AS VALOR, T.ANO FROM DW.FATO_PAGAMENTO P
	INNER JOIN DW.DIM_TEMPO T ON(ID_DATA_PAGAMENTO = ID_TEMPO)
	GROUP BY T.ANO
	
--6.	Qual o valor vendido por categoria de compras por mês?
	SELECT SUM(D.VALOR) AS VALOR, C.CATEGORIA, T.NOMEMES FROM DW.FATO_DIVIDA D
	INNER JOIN DW.DIM_CATEGORIA C ON(D.ID_CATEGORIA = C.ID_CATEGORIA)
	INNER JOIN DW.DIM_TEMPO T ON(ID_DATA_DIVIDA = ID_TEMPO)
	GROUP BY C.CATEGORIA, T.NOMEMES

--7.	Qual o valor comprado fiado comprado por mês por cada cliente?
	SELECT SUM(D.VALOR) AS VALOR, C.NOME, T.NOMEMES FROM DW.FATO_DIVIDA D
	INNER JOIN DW.DIM_CLIENTE C ON(D.ID_CLIENTE = C.ID_CLIENTE)
	INNER JOIN DW.DIM_TEMPO T ON(ID_DATA_DIVIDA = ID_TEMPO)
	GROUP BY C.NOME, T.NOMEMES

--8.	Qual a quantidade de clientes que compram fiado?
	SELECT COUNT(ID_CLIENTE) AS QUANTIDADE FROM DW.DIM_CLIENTE 
	WHERE ID_CLIENTE IN (SELECT ID_CLIENTE FROM DW.FATO_DIVIDA)
	
--9.	Qual a quantidade de clientes que compram fiado e ainda devem?
	SELECT COUNT(C.ID_CLIENTE) AS QUANTIDADE, c.NOME FROM DW.DIM_CLIENTE C
	INNER JOIN DW.FATO_DIVIDA D ON (C.ID_CLIENTE = D.ID_CLIENTE)
	WHERE C.ID_CLIENTE IN (SELECT ID_CLIENTE FROM DW.FATO_DIVIDA where D.STATUS_DIVIDA = 'PENDENTE')
	group by nome

--10. quantidade de dividas em aberto por cliente
	Select count(d.ID_divida) as quantidade from dw.fato_divida d 
	inner join dw.dim_cliente c on (d.ID_CLIENTE = c.ID_CLIENTE) 
	where d.status_divida = 'PENDENTE'
	group by d.id_cliente
--10. 

	SELECT * FROM DW.FATO_DIVIDA