CREATE DATABASE PROJETO_SAD
USE PROJETO_SAD

CREATE SCHEMA DW

CREATE TABLE DW.DIM_TEMPO (
	ID_TEMPO INT IDENTITY(1,1) NOT NULL,    
	NIVEL VARCHAR(8) NOT NULL,			
	DATA DATETIME NULL,
	DIA SMALLINT NULL,						
	DIASEMANA VARCHAR(25) NULL,			
	DIAUTIL CHAR(3) NULL,
	FERIADO CHAR(3) NULL,					
	FIMSEMANA CHAR(3) NULL,				
	QUINZENA SMALLINT NULL,
	MES SMALLINT NULL,						
	NOMEMES VARCHAR(20) NULL,			
	FIMMES CHAR(3) NULL,
	TRIMESTRE SMALLINT NULL,				
	NOMETRIMESTRE VARCHAR(20) NULL,		
	SEMESTRE SMALLINT NULL,
	NOMESEMESTRE VARCHAR(20) NULL,			
	ANO SMALLINT NOT NULL
)

ALTER TABLE DW.DIM_TEMPO ADD CONSTRAINT PK_DIM_TEMPO PRIMARY KEY (ID_TEMPO)

CREATE TABLE DW.DIM_CLIENTE (
	ID_CLIENTE INT IDENTITY(1,1) NOT NULL,
	COD_CLIENTE INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	APELIDO VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL,
	ENDERECO VARCHAR(200) NOT NULL,
	TELEFONE VARCHAR(10) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	SENHA VARCHAR(10) NOT NULL
)

ALTER TABLE DW.DIM_CLIENTE ADD CONSTRAINT PK_DIM_CLIENTE PRIMARY KEY (ID_CLIENTE)

CREATE TABLE DW.DIM_FUNCIONARIO (
	ID_FUNCIONARIO INT IDENTITY(1,1) NOT NULL,
	COD_FUNCIONARIO INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL,
	TELEFONE VARCHAR(10) NOT NULL,
	ENDERECO VARCHAR(200) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	SENHA VARCHAR(10) NOT NULL,
	SALARIO NUMERIC(10,2) NOT NULL, -- TIPO 2
	DATA_INICIO DATETIME NOT NULL,
	DATA_FIM DATETIME NULL,
	FLAG_CORRENTE VARCHAR(3) NOT NULL CHECK (FLAG_CORRENTE = 'SIM' OR FLAG_CORRENTE = 'NÃO')
)

ALTER TABLE DW.DIM_FUNCIONARIO ADD CONSTRAINT PK_DIM_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO)

CREATE TABLE DW.DIM_CATEGORIA (
	ID_CATEGORIA INT IDENTITY(1,1) NOT NULL,
	COD_CATEGORIA INT NOT NULL,
	CATEGORIA VARCHAR(50) NOT NULL
)

ALTER TABLE DW.DIM_CATEGORIA ADD CONSTRAINT PK_DIM_CATEGORIA PRIMARY KEY (ID_CATEGORIA)

CREATE TABLE DW.FATO_DIVIDA (
	ID_DIVIDA INT IDENTITY(1,1) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_FUNCIONARIO INT NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	ID_DATA_DIVIDA INT NOT NULL,
	ID_DATA_POSSIVEL_PAGAMENTO INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	STATUS_DIVIDA VARCHAR(20) NOT NULL,
	QUANTIDADE INT NOT NULL
)

ALTER TABLE DW.FATO_DIVIDA ADD CONSTRAINT PK_FATO_DIVIDA PRIMARY KEY (ID_DIVIDA)

CREATE TABLE DW.FATO_PAGAMENTO (
	ID_PAGAMENTO INT IDENTITY(1,1) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_FUNCIONARIO INT NOT NULL,
	ID_DATA_PAGAMENTO INT NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL
)

ALTER TABLE DW.FATO_PAGAMENTO ADD CONSTRAINT PK_FATO_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO)

ALTER TABLE DW.FATO_PAGAMENTO ADD CONSTRAINT FK_FATO_PAGAMENTO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DW.DIM_CLIENTE (ID_CLIENTE)
ALTER TABLE DW.FATO_PAGAMENTO ADD CONSTRAINT FK_FATO_PAGAMENTO_FUNCIOINARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES DW.DIM_FUNCIONARIO (ID_FUNCIONARIO)
ALTER TABLE DW.FATO_PAGAMENTO ADD CONSTRAINT FK_FATOPAGAMENTO_DATA FOREIGN KEY (ID_DATA_PAGAMENTO) REFERENCES DW.DIM_TEMPO (ID_TEMPO)

ALTER TABLE DW.FATO_DIVIDA ADD CONSTRAINT FK_FATO_DIVIDA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DW.DIM_CLIENTE (ID_CLIENTE)
ALTER TABLE DW.FATO_DIVIDA ADD CONSTRAINT FK_FATO_DIVIDA_FUNCIOINARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES DW.DIM_FUNCIONARIO (ID_FUNCIONARIO)
ALTER TABLE DW.FATO_DIVIDA ADD CONSTRAINT FK_FATO_DIVIDA_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES DW.DIM_CATEGORIA (ID_CATEGORIA)
ALTER TABLE DW.FATO_DIVIDA ADD CONSTRAINT FK_FATO_DIVIDA_DATA_DIVIDA FOREIGN KEY (ID_DATA_DIVIDA) REFERENCES DW.DIM_TEMPO (ID_TEMPO)
ALTER TABLE DW.FATO_DIVIDA ADD CONSTRAINT FK_FATO_DIVIDA_DATA_POSSIVEL_PAGAMENTO 
FOREIGN KEY (ID_DATA_POSSIVEL_PAGAMENTO) REFERENCES DW.DIM_TEMPO (ID_TEMPO)