-- AGREGADOS

CREATE SCHEMA AGR
DROP TABLE AGR.FATO_TOTAL_DIVIDA_CLIENTE
CREATE TABLE FATO_TOTAL_DIVIDA_CLIENTE (
	ID_TDC INT IDENTITY(1,1) NOT NULL,
	ID_TEMPO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	TOTAL_DIVIDA NUMERIC(10,2) NOT NULL
)

ALTER TABLE FATO_TOTAL_DIVIDA_CLIENTE ADD CONSTRAINT PK_TDC PRIMARY KEY (ID_TDC)

ALTER TABLE FATO_TOTAL_DIVIDA_CLIENTE ADD CONSTRAINT FK_TDC_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DW.DIM_CLIENTE (ID_CLIENTE)
ALTER TABLE FATO_TOTAL_DIVIDA_CLIENTE ADD CONSTRAINT FK_TDC_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DW.DIM_TEMPO (ID_TEMPO)

create PROCEDURE SP_CARGA_AGREGADO @DATA_CARGA DATETIME AS

	DECLARE	@cod_CLIENTE INT, @cod_DIVIDA INT, @COD_FUNCIONARIO INT, @COD_CATEGORIA INT, @DATA DATETIME,
			@VALOR NUMERIC(10,2), @STATUS_DIVIDA VARCHAR(20), @id_tempo int
	DECLARE C_CURSOR CURSOR FOR SELECT DATA_CARGA, COD_DIVIDA, COD_CLIENTE, COD_FUNCIONARIO, COD_CATEGORIA, DATA,
											 VALOR, STATUS_DIVIDA
								FROM STG.AUX_DIVIDA
	OPEN C_CURSOR
	FETCH C_CURSOR INTO @DATA_CARGA, @COD_DIVIDA, @COD_CLIENTE, @COD_FUNCIONARIO, @COD_CATEGORIA, @DATA,
											 @VALOR, @STATUS_DIVIDA
	WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @cod_CLIENTE = (SELECT ID_CLIENTE FROM DW.DIM_CLIENTE WHERE COD_CLIENTE = @COD_CLIENTE)
			SET @ID_TEMPO = (SELECT ID_TEMPO FROM DW.DIM_TEMPO WHERE DATA = @DATA_CARGA)
			SET @VALOR = (SELECT SUM(distinct(VALOR)) FROM DW.FATO_DIVIDA WHERE ID_data_divida = @ID_TEMPO AND ID_CLIENTE = @cod_CLIENTE)
			INSERT INTO AGR.FATO_TOTAL_DIVIDA_CLIENTE VALUES (@ID_TEMPO, @cod_CLIENTE, @VALOR)
			FETCH C_CURSOR INTO @DATA_CARGA, @COD_DIVIDA, @COD_CLIENTE, @COD_FUNCIONARIO, @COD_CATEGORIA, @DATA,
											 @VALOR, @STATUS_DIVIDA
		END
	CLOSE C_CURSOR
	DEALLOCATE C_CURSOR
