
CREATE TRIGGER TG_STATUS_PAGAMENTO
ON OLTP.TB_PAGAMENTO
AFTER INSERT, UPDATE
AS
	DECLARE @COD_PAGAMENTO INT, @COD_CLIENTE INT, @COD_FUNCIONARIO INT, @DATA_PAGAMENTO DATETIME, @VALOR NUMERIC(10,2),
			@VALOR_DIVIDA NUMERIC(10,2)
	DECLARE C_CURSOR CURSOR FOR SELECT COD_PAGAMENTO, COD_CLIENTE, COD_FUNCIONARIO, DATA, VALOR FROM INSERTED
	OPEN C_CURSOR
	FETCH C_CURSOR INTO @COD_PAGAMENTO, @COD_CLIENTE, @COD_FUNCIONARIO, @DATA_PAGAMENTO, @VALOR
	WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @VALOR_DIVIDA = (SELECT SUM(VALOR) FROM OLTP.TB_DIVIDA WHERE COD_CLIENTE = @COD_CLIENTE AND STATUS_DIVIDA = 'PENDENTE')
			IF @VALOR >= @VALOR_DIVIDA
				BEGIN
					UPDATE OLTP.TB_DIVIDA
					SET STATUS_DIVIDA = 'PAGO'
					WHERE COD_CLIENTE = @COD_CLIENTE
				END
			FETCH C_CURSOR INTO @COD_PAGAMENTO, @COD_CLIENTE, @COD_FUNCIONARIO, @DATA_PAGAMENTO, @VALOR
		END
	CLOSE C_CURSOR
	DEALLOCATE C_CURSOR