CREATE DATABASE PROJETO_SAD


USE PROJETO_SAD

----------------------------------------------------------------------------------------------------------------------
-- CARGA OLTP PARA STAGING

--------------------------							--------------------------
--------------------------			CLIENTE			--------------------------
--------------------------							--------------------------

CREATE PROCEDURE SP_CLIENTE_OLTP_STG @DATA_CARGA DATETIME AS
DECLARE @COD_CLIENTE INT, @NOME VARCHAR(100) ,@APELIDO VARCHAR(100), @DATA_NASCIMENTO DATETIME,
		@TELEFONE VARCHAR(11), @ENDERECO VARCHAR(200), @CPF VARCHAR(11), @SENHA VARCHAR(10)
DECLARE C_CURSOR CURSOR FOR SELECT COD_CLIENTE, NOME, APELIDO, DATA_NASCIMENTO, TELEFONE, ENDERECO, CPF, SENHA FROM OLTP.TB_CLIENTE
OPEN C_CURSOR
FETCH C_CURSOR INTO @COD_CLIENTE, @NOME, @APELIDO, @DATA_NASCIMENTO, @TELEFONE, @ENDERECO, @CPF, @SENHA
WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(EXISTS(SELECT DATA_CARGA FROM STG.AUX_CLIENTE WHERE COD_CLIENTE = @COD_CLIENTE AND DATA_CARGA = @DATA_CARGA))
			DELETE FROM STG.AUX_CLIENTE WHERE DATA_CARGA = @DATA_CARGA
		INSERT INTO STG.AUX_CLIENTE VALUES (@DATA_CARGA, @COD_CLIENTE, @NOME, @APELIDO, @DATA_NASCIMENTO, @TELEFONE, @ENDERECO, @CPF, @SENHA)
		FETCH C_CURSOR INTO @COD_CLIENTE, @NOME, @APELIDO, @DATA_NASCIMENTO, @TELEFONE, @ENDERECO, @CPF, @SENHA
	END
CLOSE C_CURSOR
DEALLOCATE C_CURSOR

TRUNCATE TABLE DW.DIM_CLIENTE
EXEC SP_CLIENTE_OLTP_STG '20180824'
EXEC SP_CLIENTE_STG_DW '20180824'
SELECT * FROM STG.VIO_CLIENTE
UPDATE OLTP.TB_CLIENTE SET ENDERECO = 'RUA C' WHERE COD_CLIENTE = 3


--------------------------								--------------------------
--------------------------			FUNCIONARIO			--------------------------
--------------------------								--------------------------

ALTER PROCEDURE SP_FUNCIONARIO_OLTP_STG @DATA_CARGA DATETIME AS
DECLARE @COD_FUNCIONARIO INT, @NOME VARCHAR(100), @DATA_NASCIMENTO DATETIME, @TELEFONE VARCHAR(11),
		@ENDERECO VARCHAR(200),@SALARIO NUMERIC(10,2), @CPF VARCHAR(11), @SENHA VARCHAR(10)

DECLARE C_CURSOR CURSOR FOR SELECT COD_FUNCIONARIO, NOME, DATA_NASCIMENTO,
		TELEFONE, ENDERECO, SALARIO, CPF, SENHA FROM OLTP.TB_FUNCIONARIO
OPEN C_CURSOR
FETCH C_CURSOR INTO @COD_FUNCIONARIO, @NOME, @DATA_NASCIMENTO,@TELEFONE, @ENDERECO, @SALARIO, @CPF, @SENHA
WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(EXISTS(SELECT DATA_CARGA FROM STG.AUX_FUNCIONARIO WHERE COD_FUNCIONARIO = @COD_FUNCIONARIO AND DATA_CARGA = @DATA_CARGA))
			DELETE FROM STG.AUX_FUNCIONARIO WHERE DATA_CARGA = @DATA_CARGA
		INSERT INTO STG.AUX_FUNCIONARIO VALUES (@DATA_CARGA, @COD_FUNCIONARIO, @NOME, @DATA_NASCIMENTO, @TELEFONE, @ENDERECO,
											    @SALARIO, @CPF, @SENHA)
		FETCH C_CURSOR INTO @COD_FUNCIONARIO, @NOME, @DATA_NASCIMENTO,@TELEFONE, @ENDERECO, @SALARIO, @CPF, @SENHA	
	END
CLOSE C_CURSOR
DEALLOCATE C_CURSOR

EXEC SP_FUNCIONARIO_OLTP_STG '20180824'
EXEC SP_FUNCIONARIO_STG_DW '20180824'
SELECT * FROM DW.DIM_FUNCIONARIO
UPDATE OLTP.TB_FUNCIONARIO SET NOME = 'JOÃO NETO', SALARIO = 1200 WHERE COD_FUNCIONARIO = 10

--------------------------								--------------------------
--------------------------			CATEGORIA			--------------------------
--------------------------								--------------------------

CREATE PROCEDURE SP_CATEGORIA_OLTP_STG @DATA_CARGA DATETIME AS
DECLARE @COD_CATEGORIA INT, @CATEGORIA VARCHAR(100)

DECLARE C_CURSOR CURSOR FOR SELECT COD_CATEGORIA, CATEGORIA FROM OLTP.TB_CATEGORIA
OPEN C_CURSOR
FETCH C_CURSOR INTO @COD_CATEGORIA, @CATEGORIA
WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(EXISTS(SELECT DATA_CARGA FROM STG.AUX_CATEGORIA WHERE COD_CATEGORIA = @COD_CATEGORIA AND DATA_CARGA = @DATA_CARGA))
			DELETE FROM STG.AUX_CATEGORIA WHERE DATA_CARGA = @DATA_CARGA
		INSERT INTO STG.AUX_CATEGORIA VALUES (@DATA_CARGA, @COD_CATEGORIA, @CATEGORIA)
		FETCH C_CURSOR INTO @COD_CATEGORIA, @CATEGORIA
	END
CLOSE C_CURSOR
DEALLOCATE C_CURSOR

--------------------------								--------------------------
--------------------------		CARGA OLTP STGING		--------------------------
--------------------------								--------------------------

CREATE PROCEDURE SP_CARGA_OLTP_STG @DATA_CARGA DATETIME AS
EXEC SP_CLIENTE_OLTP_STG @DATA_CARGA
EXEC SP_FUNCIONARIO_OLTP_STG @DATA_CARGA
EXEC SP_CATEGORIA_OLTP_STG @DATA_CARGA
