USE PROJETO_SAD

CREATE SCHEMA DW


CREATE TABLE DW.DIM_TEMPO (
	ID_TEMPO INT IDENTITY(1,1) NOT NULL,    
	NIVEL VARCHAR(8) NOT NULL,			
	DATA DATETIME NULL,
	DIA SMALLINT NULL,						
	DIASEMANA VARCHAR(25) NULL,			
	DIAUTIL CHAR(3) NULL,
	FERIADO CHAR(3) NULL,					
	FIMSEMANA CHAR(3) NULL,				
	QUINZENA SMALLINT NULL,
	MES SMALLINT NULL,						
	NOMEMES VARCHAR(20) NULL,			
	FIMMES CHAR(3) NULL,
	TRIMESTRE SMALLINT NULL,				
	NOMETRIMESTRE VARCHAR(20) NULL,		
	SEMESTRE SMALLINT NULL,
	NOMESEMESTRE VARCHAR(20) NULL,			
	ANO SMALLINT NOT NULL
)

ALTER TABLE DW.DIM_TEMPO ADD CONSTRAINT PK_DIM_TEMPO PRIMARY KEY (Id_Tempo)

CREATE TABLE DW.DIM_CLIENTE (
	ID_CLIENTE INT IDENTITY NOT NULL,
	COD_CLIENTE INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	APELIDO VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL,
	ENDERECO VARCHAR(200) NOT NULL,
	TELEFONE VARCHAR(10) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	SENHA VARCHAR(10) NOT NULL
)

CREATE TABLE DW.DIM_FUNCIONARIO (
	ID_FUNCIONARIO INT IDENTITY NOT NULL,
	COD_FUNCIONARIO INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL,
	TELEFONE VARCHAR(10) NOT NULL,
	ENDERECO VARCHAR(200) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	SENHA VARCHAR(10) NOT NULL,
	SALARIO NUMERIC(10,2) NOT NULL, -- TIPO 2
	DATA_INICIO DATETIME NOT NULL,
	DATA_FIM DATETIME NULL,
	FLAG_CORRENTE VARCHAR(3) NOT NULL CHECK (FLAG_CORRENTE = 'SIM' OR FLAG_CORRENTE = 'NÃO')
)

CREATE TABLE DW.DIM_CATEGORIA (
	ID_CATEGORIA INT IDENTITY NOT NULL,
	COD_CATEGORIA INT NOT NULL,
	CATEGORIA VARCHAR(50) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL
)

DROP TABLE DW.FATO_DIVIDA
CREATE TABLE DW.FATO_DIVIDA (
	ID_DIVIDA INT IDENTITY NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_FUNCIONARIO INT NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	ID_DATA_DIVIDA DATETIME NOT NULL,
	ID_DATA_POSSIVEL_PAGAMENTO DATETIME NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL
)

CREATE TABLE DW.FATO_PAGAMENTO (
	ID_PAGAMENTO INT IDENTITY NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_FUNCIONARIO INT NOT NULL,
	ID_DATA_PAGAMENTO DATETIME NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL
)
