USE PROJETO_SAD

CREATE SCHEMA STG

-- Area Staging

CREATE TABLE STG.AUX_CLIENTE (
	DATA_CARGA DATETIME NOT NULL,
	COD_CLIENTE INT NULL,
	NOME VARCHAR(100) NULL,
	APELIDO VARCHAR(100) NULL,
	DATA_NASCIMENTO DATETIME NULL,
	TELEFONE VARCHAR(11) NULL,
	ENDERECO VARCHAR(200) NULL,
	CPF VARCHAR(11) NULL,
	SENHA VARCHAR(10) NULL
)

CREATE TABLE STG.VIO_CLIENTE (
	DATA_CARGA DATETIME NOT NULL,
	COD_CLIENTE INT NULL,
	NOME VARCHAR(100) NULL,
	APELIDO VARCHAR(100) NULL,
	DATA_NASCIMENTO DATETIME NULL,
	TELEFONE VARCHAR(11) NULL,
	ENDERECO VARCHAR(200) NULL,
	CPF VARCHAR(11) NULL,
	SENHA VARCHAR(10) NULL,
	DATA_ERRO DATETIME NOT NULL,
	MSG_ERRO VARCHAR(100) NOT NULL
)

CREATE TABLE STG.AUX_FUNCIONARIO (
	DATA_CARGA DATETIME NOT NULL,
	COD_FUNCIONARIO INT NULL,
	NOME VARCHAR(100) NULL,
	DATA_NASCIMENTO DATETIME NULL,
	TELEFONE VARCHAR(10) NULL,
	ENDERECO VARCHAR(200) NULL,
	SALARIO NUMERIC(10,2) NULL,
	CPF VARCHAR(11) NULL,
	SENHA VARCHAR(10) NULL
)

CREATE TABLE STG.VIO_FUNCIONARIO (
	DATA_CARGA DATETIME NOT NULL,
	COD_FUNCIONARIO INT NULL,
	NOME VARCHAR(100) NULL,
	DATA_NASCIMENTO DATETIME NULL,
	TELEFONE VARCHAR(10) NULL,
	ENDERECO VARCHAR(200) NULL,
	SALARIO NUMERIC(10,2) NULL,
	CPF VARCHAR(11) NULL,
	SENHA VARCHAR(10) NULL,
	DATA_ERRO DATETIME NOT NULL,
	MSG_ERRO VARCHAR(100) NOT NULL
)

CREATE TABLE STG.AUX_DIVIDA (
	DATA_CARGA DATETIME NOT NULL,
	COD_DIVIDA INT NULL,
	COD_CLIENTE INT NOT NULL,
	COD_FUNCIONARIO INT NOT NULL,
	COD_CATEGORIA INT NOT NULL,
	DATA DATETIME NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL
)

CREATE TABLE STG.VIO_DIVIDA (
	DATA_CARGA DATETIME NOT NULL,
	COD_DIVIDA INT NULL,
	COD_CLIENTE INT NULL,
	COD_FUNCIONARIO INT NULL,
	COD_CATEGORIA INT NULL,
	DATA DATETIME NULL,
	VALOR NUMERIC(10,2) NULL,
	DATA_ERRO DATETIME NOT NULL,
	MSG_ERRO VARCHAR(100) NOT NULL
)

CREATE TABLE STG.AUX_CATEGORIA (
	DATA_CARGA DATETIME NOT NULL,
	COD_CATEGORIA INT NULL,
	CATEGORIA VARCHAR(100),
	VALOR NUMERIC(10,2) NULL
)

CREATE TABLE STG.VIO_CATEGORIA (
	DATA_CARGA DATETIME NOT NULL,
	COD_CATEGORIA INT NULL,
	CATEGORIA VARCHAR(100),
	VALOR NUMERIC(10,2) NULL,
	DATA_ERRO DATETIME NOT NULL,
	MSG_ERRO VARCHAR(100) NOT NULL
)

CREATE TABLE STG.AUX_PAGAMENTO (
	DATA_CARGA DATETIME NOT NULL,
	COD_PAGAMENTO INT NULL,
	COD_CLIENTE INT NULL,
	COD_FUNCIONARIO INT NULL,
	DATA DATETIME NULL,
	VALOR NUMERIC(10,2) NULL
)

CREATE TABLE STG.VIO_PAGAMENTO (
	DATA_CARGA DATETIME NOT NULL,
	COD_PAGAMENTO INT NULL,
	COD_CLIENTE INT NULL,
	COD_FUNCIONARIO INT NULL,
	DATA DATETIME NULL,
	VALOR NUMERIC(10,2) NULL,
	DATA_ERRO DATETIME NOT NULL,
	MSG_ERRO VARCHAR(100) NOT NULL
)
